### PR TITLE
Added a Starbucks crawling script

### PR DESCRIPTION
**Pull request by shauryachawla**
The output of the script is a list of available coffee in the Starbucks store.

### CODE REVIEW

**Comment by zombiefied** [comment]
Unless i've missed something, you don't save this into the existing json file. Doing this would be quite beneficial, and when this gets into the main branch I might jump on getting this into my combinationscript =)

**Comment by shauryachawla** [comment]
@zombiefied on it!

**Comment by shauryachawla** [comment]
Okay so now the crawler is able to update the current 'coffeeType.json' file whenever run. It syncs with the Starbucks data, and the pre-added data. =)

**Comment by DeastinY** [comment]
Very nice feature, thanks for implementing it !

**Comment by shauryachawla** [comment]
Hurray! You are welcome! And thanks for helping me out! =)

**Comment by DeastinY** [comment]
Hehe. No sweat :) How many pull requests do you still need ?

**Comment by shauryachawla** [comment]
Oh this one was my fifth. :)

**Pull request merged**
