### PR TITLE
Added Coffee Image URLs

### PR DESCRIPTION
**Pull request by shauryachawla**
I think I'm far behind the current status of this project, but coffee_crawler.py should have updated the current json file afaik. This is the updated json file along with the urls of images of the respective base coffees... :)

### CODE REVIEW

**Comment by DeastinY** [comment]
check again please :)

**Comment by shauryachawla** [comment]
@DeastinY I didn't get it.. What should I check, again?

**Comment by DeastinY** [comment]
Branch is conflicting, probably due to updates in coffeeType.json

**Comment by shauryachawla** [comment]
The files are conflicting because of amendments? Maybe I'm missing some very obvious point here, but I don't have any idea why it shows "conflicting." I just converted the coffee list to coffee dictionary. Help me out? :)

**Comment by DeastinY** [comment]
Damn those buttons. Looking good now :laughing:

**Comment by shauryachawla** [comment]
@DeastinY Thank you! But, can you please tell me why Travis CI is rejecting my version of build? I am having a hard time getting my head around this utility.

**Comment by DeastinY** [comment]
I've got to finish a paper in 2 hours, so kinda busy right now. It has often been an issue with python 3.6

**Comment by shauryachawla** [comment]
Oh no problem! Just review this merge whenever you get time. :)

**Pull request merged**
