### PR TITLE
[Issue #16]: Refactored code by following PEP8 conventions

### PR DESCRIPTION
**Pull request by raj454raj**

### CODE REVIEW

**Review by Tjzabel — APPROVED** [review]
Code is definitely improved

**Comment by DeastinY** [comment]
there seem to still be some pep8 issues :
`./main.py:4:1: F401 'collections.OrderedDict' imported but unused`

**Comment by raj454raj** [comment]
@DeastinY : Done

**Comment by DeastinY** [comment]
Hm. any comment on the renaming of order to ordered ? why past tense ?

**Comment by raj454raj** [comment]
Function name itself is `order`. I know the variable name is bad - any suggestions ?

**Comment by raj454raj** [comment]
@DeastinY : Updated.

**Comment by DeastinY** [comment]
looking good :+1:

**Comment by raj454raj** [comment]
Why closed ?

**Comment by DeastinY** [comment]
wrong button :laughing: thanks

**Pull request merged**
